### ISSUE TITLE
Sleep/jitter information not shown in table view.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#346] opened 2023-11-22 12:48 UTC
Hi,

Sleep/jitter information is not shown for callbacks in table view. Snooze icon is yellow and popup has no data.
Despite the fact that the information is present in http profile settings.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/02ab68ab-97a5-461d-b5ed-a580b2289312)
![image](https://github.com/its-a-feature/Mythic/assets/1915618/05d93384-86d2-43dd-833c-f932670d382f)

Once you run `sleep {"interval":47,"jitter":32}`, then snooze icon goes blue and now popup has sleep/jitter numbers.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/4cad48c2-678f-4317-b5f6-de3a8947ca0d)
![image](https://github.com/its-a-feature/Mythic/assets/1915618/6cff1b18-8fe5-4e48-a934-5e71074910e2)

**Comment by its-a-feature** [comment] 2023-11-22 14:06
That's currently working as intended actually. 

Mythic doesn't inherently know what "sleep" is and doesn't have any special meaning tied to any C2 Profile's parameters. That's why the sleep information is blank for all callbacks initially. Agents can specify to have certain functions within their docker containers run when commands complete; `poseidon` for example uses this feature (https://github.com/MythicAgents/poseidon/blob/master/Payload_Type/poseidon/poseidon/agentfunctions/sleep.go#L58-L75) to update that sleep parameter of the callback that issued the new `sleep` command. That's why you then see it change to blue with that information.

Next year when I get event triggers and scheduled tasks baked into Mythic is when you'll be able to automatically execute things like that on a new callback to update that information. Until then, you'd have to use the Mythic Scripting capabilities to listen for a new callback and update it yourself

**Comment by timukas** [comment] 2023-11-22 14:45
I thought since callback Metadata already has this information, then it's also in main table.

But ok. Now it's clear.

**Comment by its-a-feature** [comment] 2023-11-22 21:47
I'm gonna close this for now since it's intended behavior. If you want, you can open another issue as a feature request to adjust how that works or other ways it can be leveraged

**Closed by its-a-feature** 2023-11-22 21:47 UTC
