### ISSUE TITLE
All C2 Profiles and Payloads Offline. Host says they are running.

### ISSUE THREAD

**Issue by ZerkerEOD** [its-a-feature/Mythic#187] opened 2022-03-12 18:03 UTC
Last time this happened I performed a full update and you requested that I post here first to try and fix it. Here I am again with the same problem. All containers are offline, the http server is still running but the container is offline. Here is a screenshot of my payloads/profiles page:
![image](https://user-images.githubusercontent.com/26573385/158029323-9a31d775-ceda-42ab-8be0-bd50bb5de745.png)

Here is the response from `./mythci-cli status`:
![image](https://user-images.githubusercontent.com/26573385/158029363-1295aecc-f60a-4a0e-a509-945407960e8b.png)

Lastly, here is the event log from within mythic where it looks like it lost connection to all the containers:
![image](https://user-images.githubusercontent.com/26573385/158029400-09e585db-8564-4457-af3b-07e78a5e53b9.png)

Any quick help would be awesome. I am hoping for a way to get them to reconnect without breaking connection of active listers if possible.

**Comment by ZerkerEOD** [comment] 2022-03-12 18:13
Update, I performed the following commands:
```
./mythic-cli c2 stop
./mythic-cli payload stop
./mythic-cli c2 start
./mythic-cli payload start
```
The start commands ended with a successful connection to RabbitMQ
![image](https://user-images.githubusercontent.com/26573385/158029672-cf9102ec-bb6e-41a5-9ef9-d96e90acc03b.png)

However, still all red bubbles and offline on the interface.

**Comment by its-a-feature** [comment] 2022-03-12 18:47
Hey! I'm sorry this is happening to you, I know what's going on though at least. There's a nondeterministic bug that's happening regarding the `mythic_server`'s connection to the `mythic_postgres` database. The connection breaks, so nothing can get updated. The reason the UI thinks all of the containers are offline is because the last heartbeat time for the containers can't get updated in the database, so they appear offline (despite the containers themselves all actually running). The only way to bring things back up is to restart all of mythic (`sudo ./mythic-cli start`). All of your agents should connect back though.

One thing you can try:

- `sudo ./mythic-cli stop`
- https://github.com/its-a-feature/Mythic/blob/master/mythic-docker/app/__init__.py#L77 <-- on that line, set the value to 1
- `sudo ./mythic-cli start`

**Comment by ZerkerEOD** [comment] 2022-03-12 23:33
Just wanting to verify line 77 is `max_worker_connection = 50` and I am changing that to 1. I have done that and will report back in a couple days if they seem more stable.

**Comment by its-a-feature** [comment] 2022-03-13 03:13
yup, that's the value we're changing. odd that it doesn't work with 1, but with the smaller number it should help. Let me know how it goes

**Comment by its-a-feature** [comment] 2022-03-21 16:23
did that work for you?

**Comment by ZerkerEOD** [comment] 2022-03-21 16:40
25 did not work, they are all offline again. This time it let me change it to 1 and everything came up.  I will let it run a little bit with the value of 1 and see what happens.

**Comment by its-a-feature** [comment] 2022-03-31 00:23
hm... is there anything consistent you're seeing before it happens?

When it happens, can you run `sudo ./mythic-cli logs mythic_postgres` and share the output here? I'm trying to see if this is the same as another problem i've periodically seen where the database says there's already a transaction in progress and errors out.

**Comment by ZerkerEOD** [comment] 2022-03-31 00:33
Yeah, here you go.

```
root@ubuntu-s-2vcpu-4gb-Mythic:/opt/Mythic# ./mythic-cli logs mythic_postgres

PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-03-21 16:39:10.595 UTC [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
2022-03-21 16:39:10.596 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-03-21 16:39:10.597 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-03-21 16:39:10.608 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-03-21 16:39:10.614 UTC [22] LOG:  database system was shut down at 2022-03-21 16:37:42 UTC
2022-03-21 16:39:10.624 UTC [1] LOG:  database system is ready to accept connections
2022-03-21 16:39:17.806 UTC [29] LOG:  incomplete startup packet
2022-03-21 16:39:21.979 UTC [32] ERROR:  constraint "fk_task_token_id_refs_token" for relation "task" already exists
2022-03-21 16:39:21.979 UTC [32] STATEMENT:  ALTER TABLE "task" ADD CONSTRAINT "fk_task_token_id_refs_token" FOREIGN KEY ("token_id") REFERENCES "token" ("id")
2022-03-23 03:29:47.729 UTC [4913] ERROR:  canceling statement due to user request
2022-03-23 03:29:47.729 UTC [4913] STATEMENT:  SELECT  "_subs"."result_id" , "_fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS "_subs"("result_id", "result_vars") LEFT OUTER JOIN LATERAL (SELECT  json_build_object('operationeventlog', "operationeventlog"."root" ) AS "root" FROM  (SELECT  coalesce(json_agg("root" ORDER BY "root.pg.id" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.operator"."operator" AS "operator", "_0_root.base"."message" AS "message", "_0_root.base"."level" AS "level", "_0_root.base"."resolved" AS "resolved", "_0_root.base"."source" AS "source", 'operationeventlog' AS "__typename"       ) AS "_4_e"      ) ) AS "root", "_0_root.base"."id" AS "root.pg.id" FROM  (SELECT  *  FROM "public"."operationeventlog"  WHERE ((("public"."operationeventlog"."operation_id") = ANY((("_subs"."result_vars"#>>ARRAY['session', 'x-hasura-operations']))::integer array)) AND ((("public"."operationeventlog"."operation_id") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '0']))::integer)) AND ((("public"."operationeventlog"."deleted") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '1']))::boolean)) AND (("public"."operationeventlog"."timestamp") >= ((("_subs"."result_vars"#>>ARRAY['synthetic', '2']))::timestamp)))))   ORDER BY "id" DESC NULLS FIRST LIMIT 1 ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.operator.base"."username" AS "username", 'operator' AS "__typename"       ) AS "_2_e"      ) ) AS "operator" FROM  (SELECT  *  FROM "public"."operator"  WHERE (("_0_root.base"."operator_id") = ("id"))     ) AS "_1_root.or.operator.base"      ) AS "_3_root.or.operator" ON ('true')    ORDER BY "root.pg.id" DESC NULLS FIRST  ) AS "_5_root"      ) AS "operationeventlog"      ) AS "_fld_resp" ON ('true')      
2022-03-23 19:41:36.302 UTC [7201] ERROR:  canceling statement due to user request
2022-03-23 19:41:36.302 UTC [7201] STATEMENT:  SELECT  "_subs"."result_id" , "_fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS "_subs"("result_id", "result_vars") LEFT OUTER JOIN LATERAL (SELECT  json_build_object('operationeventlog', "operationeventlog"."root" ) AS "root" FROM  (SELECT  coalesce(json_agg("root" ORDER BY "root.pg.id" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.operator"."operator" AS "operator", "_0_root.base"."message" AS "message", "_0_root.base"."level" AS "level", "_0_root.base"."resolved" AS "resolved", "_0_root.base"."source" AS "source", 'operationeventlog' AS "__typename"       ) AS "_4_e"      ) ) AS "root", "_0_root.base"."id" AS "root.pg.id" FROM  (SELECT  *  FROM "public"."operationeventlog"  WHERE ((("public"."operationeventlog"."operation_id") = ANY((("_subs"."result_vars"#>>ARRAY['session', 'x-hasura-operations']))::integer array)) AND ((("public"."operationeventlog"."operation_id") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '0']))::integer)) AND ((("public"."operationeventlog"."deleted") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '1']))::boolean)) AND (("public"."operationeventlog"."timestamp") >= ((("_subs"."result_vars"#>>ARRAY['synthetic', '2']))::timestamp)))))   ORDER BY "id" DESC NULLS FIRST LIMIT 1 ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.operator.base"."username" AS "username", 'operator' AS "__typename"       ) AS "_2_e"      ) ) AS "operator" FROM  (SELECT  *  FROM "public"."operator"  WHERE (("_0_root.base"."operator_id") = ("id"))     ) AS "_1_root.or.operator.base"      ) AS "_3_root.or.operator" ON ('true')    ORDER BY "root.pg.id" DESC NULLS FIRST  ) AS "_5_root"      ) AS "operationeventlog"      ) AS "_fld_resp" ON ('true')      
2022-03-24 22:41:06.470 UTC [10895] ERROR:  canceling statement due to user request
2022-03-24 22:41:06.470 UTC [10895] STATEMENT:  SELECT  "_subs"."result_id" , "_fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS "_subs"("result_id", "result_vars") LEFT OUTER JOIN LATERAL (SELECT  json_build_object('operationeventlog', "operationeventlog"."root" ) AS "root" FROM  (SELECT  coalesce(json_agg("root" ORDER BY "root.pg.id" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.operator"."operator" AS "operator", "_0_root.base"."message" AS "message", "_0_root.base"."level" AS "level", "_0_root.base"."resolved" AS "resolved", "_0_root.base"."source" AS "source", 'operationeventlog' AS "__typename"       ) AS "_4_e"      ) ) AS "root", "_0_root.base"."id" AS "root.pg.id" FROM  (SELECT  *  FROM "public"."operationeventlog"  WHERE ((("public"."operationeventlog"."operation_id") = ANY((("_subs"."result_vars"#>>ARRAY['session', 'x-hasura-operations']))::integer array)) AND ((("public"."operationeventlog"."operation_id") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '0']))::integer)) AND ((("public"."operationeventlog"."deleted") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '1']))::boolean)) AND (("public"."operationeventlog"."timestamp") >= ((("_subs"."result_vars"#>>ARRAY['synthetic', '2']))::timestamp)))))   ORDER BY "id" DESC NULLS FIRST LIMIT 1 ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.operator.base"."username" AS "username", 'operator' AS "__typename"       ) AS "_2_e"      ) ) AS "operator" FROM  (SELECT  *  FROM "public"."operator"  WHERE (("_0_root.base"."operator_id") = ("id"))     ) AS "_1_root.or.operator.base"      ) AS "_3_root.or.operator" ON ('true')    ORDER BY "root.pg.id" DESC NULLS FIRST  ) AS "_5_root"      ) AS "operationeventlog"      ) AS "_fld_resp" ON ('true')      
2022-03-28 18:53:52.115 UTC [23126] ERROR:  canceling statement due to user request
2022-03-28 18:53:52.115 UTC [23126] STATEMENT:  SELECT  "_subs"."result_id" , "_fld_resp"."root" AS "result" FROM UNNEST(($1)::uuid[], ($2)::json[]) AS "_subs"("result_id", "result_vars") LEFT OUTER JOIN LATERAL (SELECT  json_build_object('operationeventlog', "operationeventlog"."root" ) AS "root" FROM  (SELECT  coalesce(json_agg("root" ORDER BY "root.pg.id" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_4_e"  FROM  (SELECT  "_3_root.or.operator"."operator" AS "operator", "_0_root.base"."message" AS "message", "_0_root.base"."level" AS "level", "_0_root.base"."resolved" AS "resolved", "_0_root.base"."source" AS "source", 'operationeventlog' AS "__typename"       ) AS "_4_e"      ) ) AS "root", "_0_root.base"."id" AS "root.pg.id" FROM  (SELECT  *  FROM "public"."operationeventlog"  WHERE ((("public"."operationeventlog"."operation_id") = ANY((("_subs"."result_vars"#>>ARRAY['session', 'x-hasura-operations']))::integer array)) AND ((("public"."operationeventlog"."operation_id") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '0']))::integer)) AND ((("public"."operationeventlog"."deleted") = ((("_subs"."result_vars"#>>ARRAY['synthetic', '1']))::boolean)) AND (("public"."operationeventlog"."timestamp") >= ((("_subs"."result_vars"#>>ARRAY['synthetic', '2']))::timestamp)))))   ORDER BY "id" DESC NULLS FIRST LIMIT 1 ) AS "_0_root.base" LEFT OUTER JOIN LATERAL (SELECT  row_to_json((SELECT  "_2_e"  FROM  (SELECT  "_1_root.or.operator.base"."username" AS "username", 'operator' AS "__typename"       ) AS "_2_e"      ) ) AS "operator" FROM  (SELECT  *  FROM "public"."operator"  WHERE (("_0_root.base"."operator_id") = ("id"))     ) AS "_1_root.or.operator.base"      ) AS "_3_root.or.operator" ON ('true')    ORDER BY "root.pg.id" DESC NULLS FIRST  ) AS "_5_root"      ) AS "operationeventlog"      ) AS "_fld_resp" ON ('true') 
```

**Comment by ZerkerEOD** [comment] 2022-04-07 15:59
I am not sure what is going on now. Logged in today and all containers were offline. Did a `./mythic-cli stop` and `./mythic-cli start` Now all my containers are crashing and coming up every few seconds. I changed the max_worker_connection to 10 and restarted again and it is still doing it.

**Comment by ZerkerEOD** [comment] 2022-04-26 19:48
It is back to all dockers claiming to start and stop over and over making Mythic unusable.

**Comment by its-a-feature** [comment] 2022-05-09 16:05
Hey! I think ubuntu or debian would be fine, but will have the same issue. There's an issue with how the database library i'm using connects to the database in an async way that non-deterministically causes an issue. The library implicitly appears to be opening transactions against the database and then due to the concurrency, also commits another transaction while that one is open, which causes the connection to the database to close over an improperly handled error for their "robust" connection. The downside is that i can't seem to catch that error anywhere to handle it myself, and i can't reliably reproduce it to confirm that any fix works. 

So, you're good to go on as you were and if it happens, a `sudo ./mythic-cli restart` should fix it for another period of time. I'm currently working on a big back-end overhaul to help get rid of this issue and a few others by using lower-level libraries which afford me greater control over what's going on.

**Comment by ZerkerEOD** [comment] 2022-05-09 16:42
Yeah, I have attached them below.

[mythic_postgres.log](https://github.com/its-a-feature/Mythic/files/8653626/mythic_postgres.log)
[mythic_rabbitmq.log](https://github.com/its-a-feature/Mythic/files/8653627/mythic_rabbitmq.log)
[mythic_server.log](https://github.com/its-a-feature/Mythic/files/8653628/mythic_server.log)

**Comment by ZerkerEOD** [comment] 2022-05-09 17:14
Yeah, I have time. Just let me know what you have and I will do it.

**Comment by its-a-feature** [comment] 2022-05-09 17:22
Ok, try this:
https://github.com/its-a-feature/Mythic/blob/master/mythic-docker/app/api/rabbitmq_api.py#L2779
Right above that line, but still in the function, add the following:
```
if not app.db_objects.is_connected:
        logger.info("app.db_objects.is_connected is false")
        logger.info("closing connection")
        await app.db_objects.close()
        logger.info("reopening connection")
        await app.db_objects.connect()
        logger.info("connected again")
```
so it'll look like:
```
async def rabbit_heartbeat_callback(message: aio_pika.IncomingMessage):
    if not app.db_objects.is_connected:
        logger.info("app.db_objects.is_connected is false")
        logger.info("closing connection")
        await app.db_objects.close()
        logger.info("reopening connection")
        await app.db_objects.connect()
        logger.info("connected again")
    async with message.process():
```
Then restart Mythic `sudo ./mythic-cli restart` and see if that fixes it

**Comment by ZerkerEOD** [comment] 2022-05-09 17:49
While trying to see if that fixed it, I ran into another error. It happened earlier this morning as well but I cannot log into the web GUI. It tells me invalid credentials and the only way to get around it is to restart the server again.

**Comment by its-a-feature** [comment] 2022-05-09 17:50
I believe that's related to the same thing. The web UI will need to take your credentials and check them against the database, but if the server's connection to the database is broken, then it won't be able to validate them and will fail closed

**Comment by ZerkerEOD** [comment] 2022-05-09 18:46
Yeah, with the above fix I am pretty much only able to log into the server for a max 4 or 5 minutes. before no longer having access because of the web UI saying invalid credentials.

**Comment by its-a-feature** [comment] 2022-05-09 19:04
hm... are you using multiple workers? or are you back to one ( https://github.com/its-a-feature/Mythic/blob/master/mythic-docker/server.py#L23)?

Can you try at this point (https://github.com/its-a-feature/Mythic/blob/master/mythic-docker/app/routes/routes.py#L48) adding the following:
```
@mythic.middleware("request")
async def check_database(request):
    if not app.db_objects.is_connected:
        try:
            logger.info("app.db_objects.is_connected is false in web request")
            logger.info("closing connection in web request")
            await app.db_objects.close()
            logger.info("reopening connection in web request")
            await app.db_objects.connect()
            logger.info("connected again in web request")
        except Exception as e:
            logger.warning(f"Failed to close/reopen database connection in web: {e}")
            return json({"error": "got database issue"})
```

**Comment by its-a-feature** [comment] 2022-05-09 19:40
Ok, I removed the `await app.db_objects.close()` line from both of those code blocks I sent you and it seems to be working for me. Granted, I can't seem to reproduce it, so what I'm doing is:

1. ./mythic-cli start
2. wait for everything to come online and sign in
3. ./mythic-cli mythic stop mythic_postgres (kill the postgres container so everything loses connections)
4. wait a few minutes to make sure all timeouts happen and the connections are actually broken (get a bunch of errors in the UI as expected)
5. ./mythic-cli mythic start mythic_postgres (bring the postgres container back online)
6. refresh the Mythic UI and go to the payloads/c2 profiles page and see that the containers are green again and I'm able to browse the website

**Comment by its-a-feature** [comment] 2022-05-09 21:16
Ok, I think i got something working. I could at least turn off the database for various periods of time and when I turned it back on, everything would come back up. That's at least the closest I can reproduce. I merged it into the master branch if you want to just pull from there and give that a try

**Comment by ZerkerEOD** [comment] 2022-05-09 21:44
I never changed that file, Originally you asked me to change https://github.com/its-a-feature/Mythic/blob/master/mythic-docker/app/__init__.py#L77 to one from default 50 I think. So that is still currently 1. So as far as the server.py file it still has 1 worker. The __init__.py is set to 1 currently as well.

I added the above code blocks and then removed the `await app.db_objects.close()` from both the routes.py and rabbitmq_api.py files on the lines you had me add. 

Stopped the database and brought it back up as you mentioned and still having the issues. This weekend I will try to do a fresh install and see if I can get it back online stable. Everything was working until I originally updated major versions. So it's possible I messed something up during the upgrade and a fresh install will fix it. The above didn't work, so if you would like to troubleshoot it further I can send you an email for a Teams meeting and do a screen share. I don't want to waste your time if you think a re-install would potentially be better. If you are interested in a teams meeting just let me know a good date and time.

**Comment by its-a-feature** [comment] 2022-05-09 22:30
Before we do a fresh install, can you do:
```
git stash
sudo ./mythic-cli stop
git pull
sudo ./mythic-cli start
```
so that it pulls in the latest changes? I tweaked a few things. If that still doesn't fix it then we can hop on a teams call

**Comment by ZerkerEOD** [comment] 2022-05-09 23:25
They are all staying offline now. I haven't seen single one come online through the web UI

**Comment by its-a-feature** [comment] 2022-05-09 23:34
but you're able to consistently access the UI? 
What's the output of `./mythic-cli logs mythic_server`?

**Comment by ZerkerEOD** [comment] 2022-05-10 00:53
Yes, I have a stable connection to the UI

**Comment by ZerkerEOD** [comment] 2022-05-10 15:49
So I just logged in again and I have what appears to be a stable connection to the UI but the UI still lists all containers as offline.

**Comment by its-a-feature** [comment] 2022-05-10 15:52
what's the output of `sudo ./mythic-cli logs mythic_server`?

**Comment by ZerkerEOD** [comment] 2022-05-10 17:52
Sorry, been a little busy today here are the logs.
[mythic_server2.log](https://github.com/its-a-feature/Mythic/files/8663859/mythic_server2.log)

**Comment by its-a-feature** [comment] 2022-05-10 23:44
hm... I don't see any errors in there outside of just not finding svg files for wrappers 🤔 If you restart, you're still unable to see any containers check in? Can you provide the output for `sudo ./mythic-cli logs [agent name]` for one of the payload containers you have checking in that used to be working?

**Comment by ZerkerEOD** [comment] 2022-05-11 21:21
@its-a-feature, hey sorry it will be a day or two before I can send that. I will try to get it to you as quickly as possible but I am working on setting up my work laptop again after a catastrophic failure.

**Comment by ZerkerEOD** [comment] 2022-06-28 15:04
@its-a-feature - Sorry its been a while, work got really busy. So I am trying to pull the logs and right now nothing is up. I did a `./mythic-cli status` and got this message:

```
C2 Profile Services:
NAME	STATE	STATUS	PORTS
[*] There are no C2 Profile containers installed; however, some do exist in the C2_Profiles folder
    To install from the C2_Profiles folder, run "sudo ./mythic-cli c2 add [profile name]"

```
I haven't removed anything and it says everything else has been up for 7 weeks. The only payload listed is Nimplant which I thought I disabled because it appears to be depreciated.

After a stop and start of the Mythic server, I am getting the same message.

After re-adding all the payloads and profiles and starting them again. I watched apfell show green on the dash board then go red shortly after. So I pulled the logs from that.

```
root@Mythic:/opt/Mythic# ./mythic-cli logs apfell
[*] To enable debug logging, set `MYTHIC_ENVIRONMENT` variable to `testing`
[*] Mythic PayloadType Version: 12
[*] PayloadType PyPi Version: 0.1.7
[*] Hostname specified as default 'hostname' value, thus will fetch and use the current hostname of the Docker container or computer

[*] Setting hostname (which should match payload type name exactly) to: apfell
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[+] Ready to go!
[*] mythic_service - Waiting for messages in mythic_service with version 12.
[*] mythic_service - total instances of apfell container running: 1
```
And it says it is still running, while the dashboard shows its not.

**Comment by ZerkerEOD** [comment] 2022-07-08 14:51
I burned the server to the ground and rebuilt it fresh. It seems to be working now after a fresh install. Been going since yesterday and everything is still online.

**Comment by ZerkerEOD** [comment] 2022-08-05 13:53
Checked last week and it was down again (we don't use it all the time). Restarted the server, and checked today to actually use it and all profiles show offline in the web GUI. the status says they have been up for 6 days.

**Comment by ZerkerEOD** [comment] 2022-08-22 22:23
@its-a-feature any additional information about this? I am now setting up a cronjob just to restart the server every week which isn't ideal. Would be nice to have it running all the time.

**Comment by its-a-feature** [comment] 2022-08-22 23:13
I'm working on a complete back-end rewrite to get rid of the issue and to improve a bunch of performance stuff. The error is caused by the underlying python library I'm using for async database connections. It throws an error in a non-deterministic fashion and breaks all of its own pooled connections which makes it "look" like all of the connections are down, but in reality the containers are running just fine and the rabbitmq messages are flowing, it's just that nothing dealing with the database can update

**Comment by ZerkerEOD** [comment] 2022-10-13 05:32
@its-a-feature, by chance, do you know the minimum requirements? I am running it on a DO box with 2cpu cores and 4 gigs of memory, and I am still having the issue but notice both CPU cores are 100% of the time at 100% and I wonder if that could be some of the issues.

**Comment by its-a-feature** [comment] 2023-04-19 15:47
With the new v3.0.0 version coming out in a few weeks I'm going to close this issue as it involved a completely different back-end system (switch from Python to GoLang). If you still encounter this issue with the new v3.0.0 code, we can re-open it

**Closed by its-a-feature** 2023-04-19 15:47 UTC
